## This file generated by InlineX::C2XS (version 0.22) using Inline::C (version 0.5301)
package Math::GMPq::V;
use strict;
use warnings;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$Math::GMPq::V::VERSION = '0.38';

DynaLoader::bootstrap Math::GMPq::V $Math::GMPq::V::VERSION;

@Math::GMPq::V::EXPORT = ();
@Math::GMPq::V::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;
